name: Scala Steward
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ~/.config/sbt
          echo "--allow-empty" >> ~/.config/sbt/sbtopts
      - uses: scala-steward-org/scala-steward-action@v2
        with:
          cache-ttl: "0s"
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
